CREATE TABLE IF NOT EXISTS user_settings (
    user_id UUID PRIMARY KEY,
    dark_mode BOOLEAN NOT NULL DEFAULT FALSE,
    cutlery BOOLEAN NOT NULL DEFAULT TRUE,
    order_tracking BOOLEAN NOT NULL DEFAULT TRUE,
    promos BOOLEAN NOT NULL DEFAULT FALSE,
    newsletter BOOLEAN NOT NULL DEFAULT TRUE
);