name: CI Docker user-service

on:
  push:
    branches:
      - develop

jobs:
  build:
    uses: GoodFoodCorp/ci-template/.github/workflows/build-deploy.yml@main
    with:
      app_name: "user-service"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      ORG_PIPELINE_TOKEN: ${{ secrets.ORG_PIPELINE_TOKEN }}
